name = "Funkin LUA"
default_targets = ["win32", "win64"]
build_directory = "build"

love_files = [
    "./main.lua",
    "./conf.lua",
    "./gameIcon.png",
    "./assets/*",
    "-*/.*",
]

shared_libraries = [
    "./discord-rpc.dll",
    "./send-presence.exe"
]
